import type { LinkState } from './src/interface';
import type { VmType, VmTarget, VmIcon, HandleEvent } from '..';
import type { DefineComponent, PropType, ComponentOptionsMixin, VNodeProps, AllowedComponentProps, ComponentCustomProps, ExtractPropTypes } from 'vue';
import type { Install, BasicType } from '../_utils';
import Link from "./src/link";
export declare const VLink: Install<DefineComponent<{
    readonly type: BasicType<PropType<VmType>, VmType | null>;
    readonly href: BasicType<PropType<string>, string | null>;
    readonly size: BasicType<PropType<string | number>, string | number | null>;
    readonly state: BasicType<PropType<LinkState>, LinkState | null>;
    readonly disabled: BasicType<BooleanConstructor, boolean>;
    readonly target: BasicType<PropType<VmTarget>, VmTarget | null>;
    readonly color: BasicType<PropType<string>, string | null>;
    readonly hoverColor: BasicType<PropType<string>, string | null>;
    readonly noCopy: BasicType<BooleanConstructor, boolean>;
    readonly noLink: BasicType<BooleanConstructor, boolean>;
    readonly beforeIcon: BasicType<PropType<VmIcon>, null>;
    readonly afterIcon: BasicType<PropType<VmIcon>, null>;
    readonly onClick: BasicType<PropType<HandleEvent>, null>;
}, {}, unknown, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, VNodeProps & AllowedComponentProps & ComponentCustomProps, Readonly<ExtractPropTypes<{
    readonly type: BasicType<PropType<VmType>, VmType | null>;
    readonly href: BasicType<PropType<string>, string | null>;
    readonly size: BasicType<PropType<string | number>, string | number | null>;
    readonly state: BasicType<PropType<LinkState>, LinkState | null>;
    readonly disabled: BasicType<BooleanConstructor, boolean>;
    readonly target: BasicType<PropType<VmTarget>, VmTarget | null>;
    readonly color: BasicType<PropType<string>, string | null>;
    readonly hoverColor: BasicType<PropType<string>, string | null>;
    readonly noCopy: BasicType<BooleanConstructor, boolean>;
    readonly noLink: BasicType<BooleanConstructor, boolean>;
    readonly beforeIcon: BasicType<PropType<VmIcon>, null>;
    readonly afterIcon: BasicType<PropType<VmIcon>, null>;
    readonly onClick: BasicType<PropType<HandleEvent>, null>;
}>>, {
    readonly type: VmType;
    readonly color: string;
    readonly beforeIcon: VmIcon;
    readonly size: string | number;
    readonly href: string;
    readonly target: VmTarget;
    readonly disabled: boolean;
    readonly afterIcon: VmIcon;
    readonly onClick: HandleEvent;
    readonly hoverColor: string;
    readonly state: LinkState;
    readonly noCopy: boolean;
    readonly noLink: boolean;
}>>;
/** link 组件实例型 */
export type LinkInstance = InstanceType<typeof Link>;
export * from './src/interface';
export default VLink;
