import type { TextDecoration } from './src/interface';
import type { VmType } from '..';
import type { DefineComponent, PropType, ComponentOptionsMixin, VNodeProps, AllowedComponentProps, ComponentCustomProps, ExtractPropTypes } from 'vue';
import type { Install, BasicType } from '../_utils';
import Text from "./src/text";
export declare const VText: Install<DefineComponent<{
    readonly type: BasicType<PropType<VmType>, VmType | null>;
    readonly size: BasicType<PropType<string | number>, string | number | null>;
    readonly color: BasicType<PropType<string>, string | null>;
    readonly background: BasicType<PropType<string>, string | null>;
    readonly block: BasicType<BooleanConstructor, boolean>;
    readonly spacing: BasicType<PropType<string | number>, string | number | null>;
    readonly lineHeight: BasicType<PropType<string | number>, string | number | null>;
    readonly indent: BasicType<PropType<string | number>, string | number | null>;
    readonly bold: BasicType<BooleanConstructor, boolean>;
    readonly decoration: BasicType<PropType<TextDecoration>, TextDecoration | null>;
    readonly padding: BasicType<PropType<string | number>, string | number | null>;
    readonly width: BasicType<PropType<string | number>, string | number | null>;
    readonly ellipsis: BasicType<BooleanConstructor, boolean>;
    readonly center: BasicType<BooleanConstructor, boolean>;
}, {}, unknown, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, VNodeProps & AllowedComponentProps & ComponentCustomProps, Readonly<ExtractPropTypes<{
    readonly type: BasicType<PropType<VmType>, VmType | null>;
    readonly size: BasicType<PropType<string | number>, string | number | null>;
    readonly color: BasicType<PropType<string>, string | null>;
    readonly background: BasicType<PropType<string>, string | null>;
    readonly block: BasicType<BooleanConstructor, boolean>;
    readonly spacing: BasicType<PropType<string | number>, string | number | null>;
    readonly lineHeight: BasicType<PropType<string | number>, string | number | null>;
    readonly indent: BasicType<PropType<string | number>, string | number | null>;
    readonly bold: BasicType<BooleanConstructor, boolean>;
    readonly decoration: BasicType<PropType<TextDecoration>, TextDecoration | null>;
    readonly padding: BasicType<PropType<string | number>, string | number | null>;
    readonly width: BasicType<PropType<string | number>, string | number | null>;
    readonly ellipsis: BasicType<BooleanConstructor, boolean>;
    readonly center: BasicType<BooleanConstructor, boolean>;
}>>, {
    readonly type: VmType;
    readonly bold: boolean;
    readonly center: boolean;
    readonly background: string;
    readonly color: string;
    readonly width: string | number;
    readonly padding: string | number;
    readonly size: string | number;
    readonly block: boolean;
    readonly spacing: string | number;
    readonly lineHeight: string | number;
    readonly indent: string | number;
    readonly decoration: TextDecoration;
    readonly ellipsis: boolean;
}>>;
/** text 组件实例类型 */
export type TextInstance = InstanceType<typeof Text>;
export * from './src/interface';
export default VText;
